
<h2 id="introduction">Introduction</h2>
<p>Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).</p>
<h2 id="data-proccessing">Data Proccessing</h2>
<p>The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.</p>
<p>The training data for this project are available here:</p>
<p>https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv</p>
<p>The test data are available here:</p>
<p>https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv</p>
<p>downloading the data</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">setwd</span>(<span class="st">&quot;C:/Users/Rodrigo/Documents/PredictionAssignment/&quot;</span>)
knitr::opts_chunk$<span class="kw">set</span>(<span class="dt">echo =</span> <span class="ot">TRUE</span>)
if (!<span class="kw">file.exists</span>(<span class="st">&quot;trainfile&quot;</span>)) {
    <span class="kw">download.file</span>(
        <span class="st">&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv&quot;</span>,
        <span class="dt">destfile =</span> <span class="st">&quot;pml-training.csv&quot;</span>)
}
if (!<span class="kw">file.exists</span>(<span class="st">&quot;testfile&quot;</span>)) {
    <span class="kw">download.file</span>(
        <span class="st">&quot;https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv&quot;</span>,
        <span class="dt">destfile =</span> <span class="st">&quot;pml-testing.csv&quot;</span>)
}

trainfile &lt;-<span class="st"> &quot;pml-training.csv&quot;</span>
testfile  &lt;-<span class="st"> &quot;pml-testing.csv&quot;</span></code></pre></div>
<p>loading libraries</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(rpart)<span class="co">#for regressive partitioning.</span>
<span class="kw">library</span>(rpart.plot)<span class="co"># for decision tree plot.</span>
<span class="kw">library</span>(caret)
<span class="kw">library</span>(corrplot)
<span class="kw">library</span>(manipulate)
<span class="kw">library</span>(xtable)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(lattice)
<span class="kw">library</span>(knitr)
<span class="kw">library</span>(markdown)
<span class="kw">library</span>(randomForest)<span class="co"># just in case i need to generate one for regression</span></code></pre></div>
<h3 id="cleaning-data-making-it-tidy.">cleaning data, making it tidy.</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datatraining &lt;-<span class="st"> </span><span class="kw">read.csv</span>(trainfile,<span class="dt">na.strings=</span><span class="kw">c</span>(<span class="st">&quot;NA&quot;</span>,<span class="st">&quot;#DIV/0!&quot;</span>,<span class="st">&quot;&quot;</span>))
datatesting &lt;-<span class="st"> </span><span class="kw">read.csv</span>(testfile,<span class="dt">na.strings=</span><span class="kw">c</span>(<span class="st">&quot;NA&quot;</span>,<span class="st">&quot;#DIV/0!&quot;</span>,<span class="st">&quot;&quot;</span>))</code></pre></div>
<p>taking out all the columns with missing values</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datatraining &lt;-<span class="st"> </span>datatraining[,<span class="kw">colSums</span>(<span class="kw">is.na</span>(datatraining)) ==<span class="st"> </span><span class="dv">0</span>]
datatesting &lt;-<span class="st"> </span>datatesting[,<span class="kw">colSums</span>(<span class="kw">is.na</span>(datatesting)) ==<span class="st"> </span><span class="dv">0</span>]</code></pre></div>
<p>taking out all variables that are not of interest</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">datatraining &lt;-<span class="st"> </span>datatraining[,-<span class="kw">c</span>(<span class="dv">1</span>:<span class="dv">7</span>)]
datatesting &lt;-<span class="st"> </span>datatesting[,-<span class="kw">c</span>(<span class="dv">1</span>:<span class="dv">7</span>)]</code></pre></div>
<p>the dimmensions of the data</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(datatraining)</code></pre></div>
<pre><code>## [1] 19622    53</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(datatesting)</code></pre></div>
<pre><code>## [1] 20 53</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(datatraining$classe)</code></pre></div>
<pre><code>## 
##    A    B    C    D    E 
## 5580 3797 3422 3216 3607</code></pre>
<h1 id="partitioning-to-allow-cross-validation">Partitioning to allow cross-validation</h1>
<p>The training data set is partionned into 2 sets: subdatatraining 60% and subdatatesting 40%.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1</span>)<span class="co">#for reproducability</span>
subsamples &lt;-<span class="st"> </span><span class="kw">createDataPartition</span>(<span class="dt">y=</span>datatraining$classe, <span class="dt">p=</span><span class="fl">0.60</span>, <span class="dt">list=</span><span class="ot">FALSE</span>)
subdatatraining &lt;-<span class="st"> </span>datatraining[subsamples, ] 
subdatatesting &lt;-<span class="st"> </span>datatraining[-subsamples, ]
<span class="kw">dim</span>(subdatatraining)</code></pre></div>
<pre><code>## [1] 11776    53</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(subdatatesting)</code></pre></div>
<pre><code>## [1] 7846   53</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(subdatatraining)</code></pre></div>
<pre><code>##   roll_belt pitch_belt yaw_belt total_accel_belt gyros_belt_x gyros_belt_y
## 2      1.41       8.07    -94.4                3         0.02         0.00
## 3      1.42       8.07    -94.4                3         0.00         0.00
## 4      1.48       8.05    -94.4                3         0.02         0.00
## 5      1.48       8.07    -94.4                3         0.02         0.02
## 7      1.42       8.09    -94.4                3         0.02         0.00
## 8      1.42       8.13    -94.4                3         0.02         0.00
##   gyros_belt_z accel_belt_x accel_belt_y accel_belt_z magnet_belt_x
## 2        -0.02          -22            4           22            -7
## 3        -0.02          -20            5           23            -2
## 4        -0.03          -22            3           21            -6
## 5        -0.02          -21            2           24            -6
## 7        -0.02          -22            3           21            -4
## 8        -0.02          -22            4           21            -2
##   magnet_belt_y magnet_belt_z roll_arm pitch_arm yaw_arm total_accel_arm
## 2           608          -311     -128      22.5    -161              34
## 3           600          -305     -128      22.5    -161              34
## 4           604          -310     -128      22.1    -161              34
## 5           600          -302     -128      22.1    -161              34
## 7           599          -311     -128      21.9    -161              34
## 8           603          -313     -128      21.8    -161              34
##   gyros_arm_x gyros_arm_y gyros_arm_z accel_arm_x accel_arm_y accel_arm_z
## 2        0.02       -0.02       -0.02        -290         110        -125
## 3        0.02       -0.02       -0.02        -289         110        -126
## 4        0.02       -0.03        0.02        -289         111        -123
## 5        0.00       -0.03        0.00        -289         111        -123
## 7        0.00       -0.03        0.00        -289         111        -125
## 8        0.02       -0.02        0.00        -289         111        -124
##   magnet_arm_x magnet_arm_y magnet_arm_z roll_dumbbell pitch_dumbbell
## 2         -369          337          513      13.13074      -70.63751
## 3         -368          344          513      12.85075      -70.27812
## 4         -372          344          512      13.43120      -70.39379
## 5         -374          337          506      13.37872      -70.42856
## 7         -373          336          509      13.12695      -70.24757
## 8         -372          338          510      12.75083      -70.34768
##   yaw_dumbbell total_accel_dumbbell gyros_dumbbell_x gyros_dumbbell_y
## 2    -84.71065                   37                0            -0.02
## 3    -85.14078                   37                0            -0.02
## 4    -84.87363                   37                0            -0.02
## 5    -84.85306                   37                0            -0.02
## 7    -85.09961                   37                0            -0.02
## 8    -85.09708                   37                0            -0.02
##   gyros_dumbbell_z accel_dumbbell_x accel_dumbbell_y accel_dumbbell_z
## 2             0.00             -233               47             -269
## 3             0.00             -232               46             -270
## 4            -0.02             -232               48             -269
## 5             0.00             -233               48             -270
## 7             0.00             -232               47             -270
## 8             0.00             -234               46             -272
##   magnet_dumbbell_x magnet_dumbbell_y magnet_dumbbell_z roll_forearm
## 2              -555               296               -64         28.3
## 3              -561               298               -63         28.3
## 4              -552               303               -60         28.1
## 5              -554               292               -68         28.0
## 7              -551               295               -70         27.9
## 8              -555               300               -74         27.8
##   pitch_forearm yaw_forearm total_accel_forearm gyros_forearm_x
## 2         -63.9        -153                  36            0.02
## 3         -63.9        -152                  36            0.03
## 4         -63.9        -152                  36            0.02
## 5         -63.9        -152                  36            0.02
## 7         -63.9        -152                  36            0.02
## 8         -63.8        -152                  36            0.02
##   gyros_forearm_y gyros_forearm_z accel_forearm_x accel_forearm_y
## 2            0.00           -0.02             192             203
## 3           -0.02            0.00             196             204
## 4           -0.02            0.00             189             206
## 5            0.00           -0.02             189             206
## 7            0.00           -0.02             195             205
## 8           -0.02            0.00             193             205
##   accel_forearm_z magnet_forearm_x magnet_forearm_y magnet_forearm_z
## 2            -216              -18              661              473
## 3            -213              -18              658              469
## 4            -214              -16              658              469
## 5            -214              -17              655              473
## 7            -215              -18              659              470
## 8            -213               -9              660              474
##   classe
## 2      A
## 3      A
## 4      A
## 5      A
## 7      A
## 8      A</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(subdatatesting)</code></pre></div>
<pre><code>##    roll_belt pitch_belt yaw_belt total_accel_belt gyros_belt_x
## 1       1.41       8.07    -94.4                3         0.00
## 6       1.45       8.06    -94.4                3         0.02
## 12      1.43       8.18    -94.4                3         0.02
## 13      1.42       8.20    -94.4                3         0.02
## 15      1.45       8.20    -94.4                3         0.00
## 16      1.48       8.15    -94.4                3         0.00
##    gyros_belt_y gyros_belt_z accel_belt_x accel_belt_y accel_belt_z
## 1             0        -0.02          -21            4           22
## 6             0        -0.02          -21            4           21
## 12            0        -0.02          -22            2           23
## 13            0         0.00          -22            4           21
## 15            0         0.00          -21            2           22
## 16            0         0.00          -21            4           23
##    magnet_belt_x magnet_belt_y magnet_belt_z roll_arm pitch_arm yaw_arm
## 1             -3           599          -313     -128      22.5    -161
## 6              0           603          -312     -128      22.0    -161
## 12            -2           602          -319     -128      21.5    -161
## 13            -3           606          -309     -128      21.4    -161
## 15            -1           597          -310     -129      21.4    -161
## 16             0           592          -305     -129      21.3    -161
##    total_accel_arm gyros_arm_x gyros_arm_y gyros_arm_z accel_arm_x
## 1               34        0.00        0.00       -0.02        -288
## 6               34        0.02       -0.03        0.00        -289
## 12              34        0.02       -0.03        0.00        -288
## 13              34        0.02       -0.02       -0.02        -287
## 15              34        0.02        0.00       -0.03        -289
## 16              34        0.02        0.00       -0.03        -289
##    accel_arm_y accel_arm_z magnet_arm_x magnet_arm_y magnet_arm_z
## 1          109        -123         -368          337          516
## 6          111        -122         -369          342          513
## 12         111        -123         -363          343          520
## 13         111        -124         -372          338          509
## 15         111        -124         -374          342          510
## 16         109        -121         -367          340          509
##    roll_dumbbell pitch_dumbbell yaw_dumbbell total_accel_dumbbell
## 1       13.05217      -70.49400    -84.87394                   37
## 6       13.38246      -70.81759    -84.46500                   37
## 12      13.10321      -70.45975    -84.89472                   37
## 13      13.38246      -70.81759    -84.46500                   37
## 15      13.07949      -70.67116    -84.69053                   37
## 16      13.35069      -70.25176    -85.03639                   37
##    gyros_dumbbell_x gyros_dumbbell_y gyros_dumbbell_z accel_dumbbell_x
## 1                 0            -0.02             0.00             -234
## 6                 0            -0.02             0.00             -234
## 12                0            -0.02             0.00             -233
## 13                0            -0.02            -0.02             -234
## 15                0            -0.02             0.00             -234
## 16                0            -0.02             0.00             -233
##    accel_dumbbell_y accel_dumbbell_z magnet_dumbbell_x magnet_dumbbell_y
## 1                47             -271              -559               293
## 6                48             -269              -558               294
## 12               47             -270              -554               291
## 13               48             -269              -552               302
## 15               47             -270              -554               294
## 16               48             -271              -554               297
##    magnet_dumbbell_z roll_forearm pitch_forearm yaw_forearm
## 1                -65         28.4         -63.9        -153
## 6                -66         27.9         -63.9        -152
## 12               -65         27.5         -63.8        -152
## 13               -69         27.2         -63.9        -151
## 15               -63         27.2         -63.9        -151
## 16               -73         27.1         -64.0        -151
##    total_accel_forearm gyros_forearm_x gyros_forearm_y gyros_forearm_z
## 1                   36            0.03            0.00           -0.02
## 6                   36            0.02           -0.02           -0.03
## 12                  36            0.02            0.02           -0.03
## 13                  36            0.00            0.00           -0.03
## 15                  36            0.00           -0.02           -0.02
## 16                  36            0.02            0.00            0.00
##    accel_forearm_x accel_forearm_y accel_forearm_z magnet_forearm_x
## 1              192             203            -215              -17
## 6              193             203            -215               -9
## 12             191             203            -215              -11
## 13             193             205            -215              -15
## 15             192             201            -214              -16
## 16             194             204            -215              -13
##    magnet_forearm_y magnet_forearm_z classe
## 1               654              476      A
## 6               660              478      A
## 12              657              478      A
## 13              655              472      A
## 15              656              472      A
## 16              656              471      A</code></pre>
<p>lets see if any patterns emerge! using correlation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corrPlot &lt;-<span class="st"> </span><span class="kw">cor</span>(subdatatraining[, -<span class="dv">53</span>])
plot1 &lt;-<span class="st"> </span><span class="kw">corrplot</span>(corrPlot, <span class="dt">method=</span><span class="st">&quot;color&quot;</span>)</code></pre></div>
<div class="figure">
<img src="figure/unnamed-chunk-8-1.png" alt="plot of chunk unnamed-chunk-8" />
<p class="caption">plot of chunk unnamed-chunk-8</p>
</div>
<p>lets get a better look at the frequency of levels in the subtraining data set. level A in the red is the more frequent occurance with over 4000 and level D in the yellow has the lease with about 2500.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plot2 &lt;-<span class="st"> </span><span class="kw">plot</span>(subdatatraining$classe, <span class="dt">col=</span><span class="kw">rainbow</span>(<span class="dv">20</span>), <span class="dt">main=</span><span class="st">&quot;Levels of classe within the subdatatraining dataset&quot;</span>, <span class="dt">xlab=</span><span class="st">&quot;classe levels&quot;</span>, <span class="dt">ylab=</span><span class="st">&quot;Frequency&quot;</span>)</code></pre></div>
<div class="figure">
<img src="figure/unnamed-chunk-9-1.png" alt="plot of chunk unnamed-chunk-9" />
<p class="caption">plot of chunk unnamed-chunk-9</p>
</div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plot2</code></pre></div>
<pre><code>##      [,1]
## [1,]  0.7
## [2,]  1.9
## [3,]  3.1
## [4,]  4.3
## [5,]  5.5</code></pre>
<h2 id="prediction-models">Prediction Models</h2>
<p>A prediction model using a decision tree.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model1 &lt;-<span class="st"> </span><span class="kw">rpart</span>(classe ~<span class="st"> </span>., <span class="dt">data=</span>subdatatraining, <span class="dt">method=</span><span class="st">&quot;class&quot;</span>)
prediction1 &lt;-<span class="st"> </span><span class="kw">predict</span>(model1, subdatatesting, <span class="dt">type =</span> <span class="st">&quot;class&quot;</span>)
plot3 &lt;-<span class="st"> </span><span class="kw">rpart.plot</span>(model1, <span class="dt">main=</span><span class="st">&quot;Classification Tree&quot;</span>, <span class="dt">extra=</span><span class="dv">102</span>, <span class="dt">under=</span><span class="ot">TRUE</span>, <span class="dt">faclen=</span><span class="dv">0</span>)</code></pre></div>
<div class="figure">
<img src="figure/unnamed-chunk-10-1.png" alt="plot of chunk unnamed-chunk-10" />
<p class="caption">plot of chunk unnamed-chunk-10</p>
</div>
<p>lets test our results</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">confusionMatrix</span>(prediction1, subdatatesting$classe)</code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2064  313   34  154   44
##          B   49  708   60   23   71
##          C   70  305 1168  125  188
##          D   31   93  100  863  106
##          E   18   99    6  121 1033
## 
## Overall Statistics
##                                          
##                Accuracy : 0.7438         
##                  95% CI : (0.734, 0.7534)
##     No Information Rate : 0.2845         
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
##                                          
##                   Kappa : 0.6744         
##  Mcnemar&#39;s Test P-Value : &lt; 2.2e-16      
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9247  0.46640   0.8538   0.6711   0.7164
## Specificity            0.9029  0.96792   0.8938   0.9497   0.9619
## Pos Pred Value         0.7911  0.77717   0.6293   0.7234   0.8089
## Neg Pred Value         0.9679  0.88320   0.9666   0.9364   0.9377
## Prevalence             0.2845  0.19347   0.1744   0.1639   0.1838
## Detection Rate         0.2631  0.09024   0.1489   0.1100   0.1317
## Detection Prevalence   0.3325  0.11611   0.2366   0.1521   0.1628
## Balanced Accuracy      0.9138  0.71716   0.8738   0.8104   0.8391</code></pre>
<p>second prediction model using random forest.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model2 &lt;-<span class="st"> </span><span class="kw">randomForest</span>(classe ~. , <span class="dt">data=</span>subdatatraining, <span class="dt">method=</span><span class="st">&quot;class&quot;</span>)
prediction2 &lt;-<span class="st"> </span><span class="kw">predict</span>(model2, subdatatesting, <span class="dt">type =</span> <span class="st">&quot;class&quot;</span>)
<span class="kw">confusionMatrix</span>(prediction2, subdatatesting$classe)</code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    A    B    C    D    E
##          A 2226    5    0    0    0
##          B    5 1509    6    0    0
##          C    1    4 1359   14    0
##          D    0    0    3 1271    5
##          E    0    0    0    1 1437
## 
## Overall Statistics
##                                           
##                Accuracy : 0.9944          
##                  95% CI : (0.9925, 0.9959)
##     No Information Rate : 0.2845          
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
##                                           
##                   Kappa : 0.9929          
##  Mcnemar&#39;s Test P-Value : NA              
## 
## Statistics by Class:
## 
##                      Class: A Class: B Class: C Class: D Class: E
## Sensitivity            0.9973   0.9941   0.9934   0.9883   0.9965
## Specificity            0.9991   0.9983   0.9971   0.9988   0.9998
## Pos Pred Value         0.9978   0.9928   0.9862   0.9937   0.9993
## Neg Pred Value         0.9989   0.9986   0.9986   0.9977   0.9992
## Prevalence             0.2845   0.1935   0.1744   0.1639   0.1838
## Detection Rate         0.2837   0.1923   0.1732   0.1620   0.1832
## Detection Prevalence   0.2843   0.1937   0.1756   0.1630   0.1833
## Balanced Accuracy      0.9982   0.9962   0.9952   0.9936   0.9982</code></pre>
<h2 id="evaluatin-of-sample-error-using-4-fold-cross-validation.">Evaluatin of sample error, using 4 fold cross validation.</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rf1&lt;-<span class="st"> </span><span class="kw">train</span>(<span class="dt">x=</span>subdatatraining[,-<span class="dv">53</span>],<span class="dt">y=</span>subdatatraining$classe,<span class="dt">method=</span><span class="st">&quot;rf&quot;</span>,
                <span class="dt">trControl=</span><span class="kw">trainControl</span>(<span class="dt">method =</span> <span class="st">&quot;cv&quot;</span>, <span class="dt">number =</span> <span class="dv">4</span>),
                <span class="dt">data=</span>subdatatraining,<span class="dt">do.trace=</span>F,<span class="dt">ntree=</span><span class="dv">250</span>)
rf1</code></pre></div>
<pre><code>## Random Forest 
## 
## 11776 samples
##    52 predictor
##     5 classes: &#39;A&#39;, &#39;B&#39;, &#39;C&#39;, &#39;D&#39;, &#39;E&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (4 fold) 
## Summary of sample sizes: 8832, 8832, 8831, 8833 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy   Kappa      Accuracy SD  Kappa SD   
##    2    0.9865826  0.9830257  0.002520887  0.003187298
##   27    0.9873472  0.9839935  0.001826161  0.002310007
##   52    0.9798735  0.9745387  0.003989264  0.005042732
## 
## Accuracy was used to select the optimal model using  the largest value.
## The final value used for the model was mtry = 27.</code></pre>
<p>in sample error and out of sample error.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">predictiontrainingrf1 &lt;-<span class="st"> </span><span class="kw">predict</span>(rf1$finalModel,<span class="dt">newdata=</span>subdatatraining)
insampleerrorforrf1&lt;-<span class="st"> </span><span class="dv">100</span>-<span class="st"> </span>(<span class="kw">mean</span>((predictiontrainingrf1 ==<span class="st"> </span>subdatatraining$classe)*<span class="dv">1</span>)*<span class="dv">100</span>)
insampleerrorforrf1</code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">predictiontestingrf1 &lt;-<span class="st"> </span><span class="kw">predict</span>(rf1,subdatatesting)
outofsampleerrorrf1 &lt;-<span class="st"> </span><span class="dv">100</span> -(<span class="kw">mean</span>((predictiontestingrf1 ==<span class="st"> </span>subdatatesting$classe)*<span class="dv">1</span>)*<span class="dv">100</span>)
outofsampleerrorrf1</code></pre></div>
<pre><code>## [1] 0.7519755</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">predictiontestingrf1 &lt;-<span class="st"> </span><span class="kw">predict</span>(rf1,datatesting[,-<span class="dv">53</span>])
predictiontestingrf1</code></pre></div>
<pre><code>##  [1] B A B A A E D B A A B C B A E E A B B B
## Levels: A B C D E</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>(predictiontestingrf1)</code></pre></div>
<pre><code>## predictiontestingrf1
## A B C D E 
## 7 8 1 1 3</code></pre>
<h2 id="decisionconclusion">Decision/Conclusion</h2>
<p>Random Forest algorithm performed better than Decision Trees. Accuracy for Random Forest model was 0.9944 (95% CI: (0.9925, 0.9959)) compared to 0.7438 (95% CI: (0.734, 0.7534)) for Decision Tree model. The random Forest model is choosen. The accuracy of the model is 0.9929. With an accuracy above 99% on our cross-validation data, we can expect that very few, or none, of the test samples will be missclassified.</p>
<pre><code>    **Random forests are suitable when to handling a large number of inputs, especially when the interactions between variables are unknown.
    **Random forest&#39;s built in cross-validation component that gives an unbiased estimate of the forest&#39;s out-of-sample (or bag) (OOB) error rate.
    **A Random forest can handle unscaled variables and categorical variables. This is more forgiving with the cleaning of the data.
    </code></pre>
<h2 id="index-including-plots">Index Including Plots</h2>
<p>corrPlot &lt;- cor(subdatatraining[, -53]) corrplot(corrPlot, method=&quot;color&quot;)</p>
<p>plot(subdatatraining$classe, col=rainbow(20), main=&quot;Levels of classe within the subTraining dataset&quot;, xlab=&quot;classe levels&quot;, ylab=&quot;Frequency&quot;) rpart.plot(model1, main=&quot;Classification Tree&quot;, extra=102, under=TRUE, faclen=0)</p>
<p>model1 &lt;- rpart(classe ~ ., data=subdatatraining, method=&quot;class&quot;) prediction1 &lt;- predict(model1, subdatatesting, type = &quot;class&quot;) rpart.plot(model1, main=&quot;Classification Tree&quot;, extra=102, under=TRUE, faclen=0)</p>

